/*
 * This source file was generated by the Gradle 'init' task
 */
package lab02.ex3;

public class App {

    public static void main(String[] args) {
        
        String figura = args[0];
        int dimensaoUm = Integer.parseInt(args[1]);

        if (figura.equals("triangulo")) {

            for (int i = 0; i < dimensaoUm; i++) {
                
                IO.print("*".repeat(i + 1));
                IO.println();
            }
        }

        if (figura.equals("losango")) {

            // Necessário ainda implementar a impressão do losango

            for (int i = 0; i < dimensaoUm; i++) {

            }

        }

        if (figura.equals("retangulo")) {

            int dimensaoDois = Integer.parseInt(args[2]);

            for (int i = 0; i < dimensaoDois; i++) {

                if (i == 0 || i == dimensaoDois - 1) {
                    IO.print("*".repeat(dimensaoUm));
                } else {
                    IO.print("*");
                    IO.print(" ".repeat(dimensaoUm - 2));
                    IO.print("*");
                }

                IO.println();
            }
        }
    }
}