/*
 * This source file was generated by the Gradle 'init' task
 */
package lab02.ex2;
import java.util.Random;

public class App {

    public static void main(String[] args) {

        Random rnd = new Random();
        int n = rnd.nextInt(1, 101);
        int tentativas = 1;
        int palpite;

        do {
            String buffer = IO.readln("Entre com um palpite para adivinhar um número entre 1 a 100: ");
            palpite = Integer.parseInt(buffer);

            if (palpite == n) {
                IO.println("Parabéns, você acertou em " + tentativas + " tentativas!");
            } else if (palpite > n) {
                IO.println("O número é menor do que o seu palpite.");
                tentativas++;
            } else if (palpite < n) {
                IO.println("O número é maior do que o seu palpite.");
                tentativas++;
            }
          
        } while (palpite != n);
    }
}
