/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        String buffer, nome;
        int escolha;

        Personagem persona = new Personagem();

        IO.println("- [1] Atribuir nome ao personagem");
        IO.println("- [2] Usar magia de poder moderado");
        IO.println("- [3] Usar magia de poder alto");
        IO.println("- [4] Tomar poção");
        IO.println("- [5] Verificar informações do personagem");
        IO.println("- [6] Sair");

        while (true) {

            buffer = IO.readln("> Escolha uma das opções: ");

            escolha = Integer.parseInt(buffer);

            if (escolha == 1) {
                nome = IO.readln("--> Entre com o nome do personagem: ");
                persona.atribuirNome(nome);

            } else if (escolha == 2) {
                persona.usarMagiaPoderModerado();

                IO.println("* -25 Mana!");

            } else if (escolha == 3) {
                persona.usarMagiaPoderAlto();

                IO.println("* -50 Mana!");
                IO.println("* -35 Vida!");

            } else if (escolha == 4) {
                persona.tomarPoção();

                IO.println("* +50 Vida!");
                IO.println("* +10 Mana!");

            } else if (escolha == 5) {
                IO.println("* Nome do personagem: " + persona.obterNome());
                IO.println("* Quantidade de Vida: " + persona.obterValorVida());
                IO.println("* Quantidade de Mana: " + persona.obterValorMana());

            } else if (escolha == 6) {
                break;
            } else {
                IO.println("!!! Erro: Escolha inválida");
            }
        }
    }
}
