/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        String buffer;
        String objeto = "Nenhum";
        int escolha;

        IO.println("- [1] Colocar objeto para bater");
        IO.println("- [2] Pressionar botão de ligar/desligar");
        IO.println("- [3] Incrementar velocidade da batedeira (1-10)");
        IO.println("- [4] Decrementar velocidade da batedeira (1-10)");
        IO.println("- [5] Verificar informações");
        IO.println("- [6] Sair");

        Batedeira bat = new Batedeira();

        while (true) {

            buffer = IO.readln("> Entre com uma das opções: ");
            escolha = Integer.parseInt(buffer);

            if (escolha == 1) {
                objeto = IO.readln("--> Defina um objeto para bater: ");
                bat.atribuirObjetoParaBater(objeto);

            } else if (escolha == 2) {
                bat.pressionarBotaoDeLigar();

            } else if (escolha == 3) {
                bat.incrementarVelocidade();

            } else if (escolha == 4) {
                bat.decrementarVelocidade();
            
            } else if (escolha == 5) {
                IO.println("* Objeto para bater: " + bat.obterObjetoParaBater());
                IO.println("* Estado da batedeira: " + bat.obterEstadoBatedeira());
                IO.println("* Velocidade da batedeira: " + bat.obterVelocidade());

            } else if (escolha == 6) {
                break;

            } else {
                IO.println("Erro: Escolha inválida");
            }
        }

    }
}
