/*
 * This source file was generated by the Gradle 'init' task
 */
package lab02.ex1;

public class App {

    public static void main(String[] args) {

        String mes, estacao;
        int dia;

        dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        mes = IO.readln("Entre com o mês: ").toLowerCase();

        estacao = switch (mes) {
            case "abril", "maio" -> "Outono"; 
            case "julho", "agosto" -> "Inverno";
            case "outubro", "novembro" -> "Primavera";
            case "janeiro", "fevereiro" -> "Verão";
            case "março" -> (dia < 20) ? "Verão" : "Outono";
            case "junho" -> (dia < 21) ? "Outono" : "Inverno";
            case "setembro" -> (dia < 22) ? "Inverno" : "Primavera";
            case "dezembro" -> (dia < 21) ? "Primavera" : "Verão";
            default -> throw new RuntimeException("Erro: Mês inválido");
        };

        IO.println(estacao);
    }
}