/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        String buffer;
        int escolha, valor;

        IO.println("- [1] Atribuir valor");
        IO.println("- [2] Incrementar valor por um");
        IO.println("- [3] Obter valor atual");
        IO.println("- [4] Sair");

        Contador cont = new Contador();

        while (true) {
            buffer = IO.readln("Escolha uma das opções: ");
        
            escolha = Integer.parseInt(buffer);

            if (escolha == 1) {
               buffer = IO.readln("Entre um valor para atribuir: ");
                valor = Integer.parseInt(buffer);

               cont.atribuirValor(valor);

            } else if (escolha == 2) {
                cont.incrementarUm();

            } else if (escolha == 3) {
                valor = cont.obterValorAtual();
                IO.println("Valor atual: " + valor);

            } else if (escolha == 4) {
                break;

            } else {
                IO.println("Erro: Escolha inválida");

            }
        }
    }
}
