/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Carro fusca = new Carro();

        fusca.acelerar(10);
        IO.println(fusca.obterVelocidadeAtual());

    }
}